In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv

In [2]:
df_train =pd.read_csv(r'C:\Users\SHARJEEL FAROOQUI\Downloads\dataset\Train.csv')
df_test =pd.read_csv(r'C:\Users\SHARJEEL FAROOQUI\Downloads\dataset\Test.csv')

In [3]:
df_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [4]:
df_test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [5]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [6]:
df_test.isnull().sum()

Item_Identifier                 0
Item_Weight                   976
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [8]:
df_train['Item_Weight'].describe()

count    7060.000000
mean       12.857645
std         4.643456
min         4.555000
25%         8.773750
50%        12.600000
75%        16.850000
max        21.350000
Name: Item_Weight, dtype: float64

In [9]:
df_train['Item_Weight'].fillna(df_train['Item_Weight'].mean(), inplace=True)
df_test['Item_Weight'].fillna(df_test['Item_Weight'].mean(), inplace=True)

In [10]:
df_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [11]:
df_train.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [12]:
#no null value in item weight
df_train['Item_Weight'].describe()

count    8523.000000
mean       12.857645
std         4.226124
min         4.555000
25%         9.310000
50%        12.857645
75%        16.000000
max        21.350000
Name: Item_Weight, dtype: float64

In [13]:
df_train['Outlet_Size'].mode()

0    Medium
Name: Outlet_Size, dtype: object

In [14]:
df_train['Outlet_Size'].value_counts()

Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

In [15]:
df_train['Outlet_Size'].fillna(df_train['Outlet_Size'].mode()[0], inplace=True)
df_test['Outlet_Size'].fillna(df_test['Outlet_Size'].mode()[0], inplace=True)

In [16]:
df_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Medium,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [17]:
df_train.isnull().sum()
# now we can observe that there is no null value means no missing value

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [18]:
df_train.drop(['Item_Identifier', 'Outlet_Identifier'],axis=1,inplace=True)
df_test.drop(['Item_Identifier', 'Outlet_Identifier'],axis=1,inplace=True)

In [19]:
df_train

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,9.300,Low Fat,0.016047,Dairy,249.8092,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,5.920,Regular,0.019278,Soft Drinks,48.2692,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,17.500,Low Fat,0.016760,Meat,141.6180,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,1998,Medium,Tier 3,Grocery Store,732.3800
4,8.930,Low Fat,0.000000,Household,53.8614,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...
8518,6.865,Low Fat,0.056783,Snack Foods,214.5218,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,8.380,Regular,0.046982,Baking Goods,108.1570,2002,Medium,Tier 2,Supermarket Type1,549.2850
8520,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,7.210,Regular,0.145221,Snack Foods,103.1332,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,14.800,Low Fat,0.044878,Soft Drinks,75.4670,1997,Small,Tier 1,Supermarket Type1,765.6700

In [20]:
pip install dtale

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dtale in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (3.7.0)
Requirement already satisfied: Flask<2.3 in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.1.2)
Requirement already satisfied: squarify in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.4.3)
Requirement already satisfied: xlrd in c:\programdata\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (from dtale) (3.5.2)
Requirement already satisfied: numpy in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (1.24.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.9.1)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.1.0)
Requirement already satisfied: missingno in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.5.2)
Requirement already satisfied: cycler in c:\programdata\anaconda3\lib\site-packages (from dtale) (0.11.0)
Requirement already satisfied: statsmodels in c:\programdata\anaconda3\lib\site-packages (from dtale) (0.13.2)
Requirement already satisfied: xarray in c:\programdata\anaconda3\lib\site-packages (from dtale) (0.20.1)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from dtale) (2022.9.14)
Requirement already satisfied: future>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from dtale) (0.18.2)
Requirement already satisfied: lz4 in c:\programdata\anaconda3\lib\site-packages (from dtale) (3.1.3)
Requirement already satisfied: kaleido in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.2.1)
Requirement already satisfied: dash in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (2.14.1)
Requirement already satisfied: dash-bootstrap-components<=1.3.1 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (1.3.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from dtale) (4.11.1)
Requirement already satisfied: werkzeug<2.3 in c:\programdata\anaconda3\lib\site-packages (from dtale) (2.0.3)
Requirement already satisfied: networkx in c:\programdata\anaconda3\lib\site-packages (from dtale) (2.8.4)
Requirement already satisfied: plotly in c:\programdata\anaconda3\lib\site-packages (from dtale) (5.9.0)
Requirement already satisfied: dash-daq in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.5.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.0.2)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.4.4)
Requirement already satisfied: itsdangerous in c:\programdata\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: flask-ngrok in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.0.25)
Requirement already satisfied: openpyxl!=3.2.0b1 in c:\programdata\anaconda3\lib\site-packages (from dtale) (3.0.10)
Requirement already satisfied: strsimpy in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.2.1)
Requirement already satisfied: Flask-Compress in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (1.14)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (from dtale) (0.11.2)
Requirement already satisfied: dash-colorscales in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dtale) (0.0.4)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from dtale) (2.28.1)
Requirement already satisfied: retrying in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from dash->dtale) (1.5.5)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (4.8.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from dash->dtale) (63.4.1)
Requirement already satisfied: importlib-metadata in c:\programdata\anaconda3\lib\site-packages (from dash->dtale) (4.11.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (5.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (2.0.0)
Requirement already satisfied: ansi2html in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from dash->dtale) (1.8.0)
Requirement already satisfied: click>=5.1 in c:\programdata\anaconda3\lib\site-packages (from Flask<2.3->dtale) (8.0.4)
Requirement already satisfied: Jinja2>=2.10.1 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from Flask<2.3->dtale) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from plotly->dtale) (8.0.1)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->dtale) (2.3.1)
Requirement already satisfied: brotli in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (from Flask-Compress->dtale) (1.1.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->dtale) (1.4.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas->dtale) (2022.1)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->dtale) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->dtale) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->dtale) (1.26.11)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->dtale) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->dtale) (1.1.0)
Requirement already satisfied: patsy>=0.5.2 in c:\programdata\anaconda3\lib\site-packages (from statsmodels->dtale) (0.5.2)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click>=5.1->Flask<2.3->dtale) (0.4.5)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.10.1->Flask<2.3->dtale) (2.0.1)
Requirement already satisfied: zipp>=0.5 in c:\programdata\anaconda3\lib\site-packages (from importlib-metadata->dash->dtale) (3.8.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install jinja2

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jinja2 in c:\users\sharjeel farooqui\appdata\roaming\python\python39\site-packages (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2) (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from markupsafe import escape

In [ ]:
pip uninstall flask

In [ ]:
pip install flask

In [ ]:
import dtale

In [ ]:
dtale.show(df_train)